[setup]
python = "3.12.1"
gcc = true

[install]
cmd = """
python -m venv --copies /opt/venv
. /opt/venv/bin/activate
pip install -r requirements.txt
"""

[start]
cmd = """
. /opt/venv/bin/activate
python manage.py migrate && gunicorn hashflix.wsgi --log-file -
"""
